### ISSUE TITLE
New install-script run with "sudo" creates wrong ownership of folders

### ISSUE THREAD

**Issue by Simonlovald** [ludwig247/DeSCAM#116] opened 2020-09-30 13:46 UTC
In order to run all parts of the install script, it is necessary to run with root-permissions.
This results in the generated folders having root-ownership. 
This prevents all further runs of the tool, because it has no permission to run the binaries.

To fix, it is necessary to give following command in terminal from DeSCAM root-folder after installation:
sudo chown -R $USER ./bin

**Comment by J3s7r** [comment] 2020-11-16 10:59
Bash install script is deprecated and has been removed from the project. Please follow the installation instructions given in Install.md

Please confirm if the issue is resolved with the new install procedure to close the issue.

**Closed** 2020-11-18 11:47 UTC
Labels: fixed
